export { default as Accordion } from "./Accordion"
export { default as Card } from "./Card"
export { default as Feature } from "./Feature"
export { default as Footer } from "./Footer"
export { default as Form } from "./Form"
export { default as Header } from "./Header"
export { default as Jumbotron } from "./Jumbotron"
export { default as Loading } from "./Loading"
export { default as OptForm } from "./Opt-Form"
export { default as Player } from "./Player"
export { default as Profiles } from "./Profiles"

